#
# print schema: yarn backstage-cli config:schema
# check schema: yarn backstage-cli config:check
#

organization:
  name: GrayC GmbH

app:
  title: Backstage
  baseUrl: http://localhost:3000

backend:
  baseUrl: http://localhost:7007
  listen: 0.0.0.0:7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, POST, PUT, DELETE]
    credentials: true
  database:
    client: sqlite3
    connection: ':memory:'
  cache:
    store: memory
    workingDirectory: /tmp/backstage

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

auth:
  environment: production
  providers:
    github:
      production:
        clientId: ${GITHUB_CLIENT_ID}
        clientSecret: ${GITHUB_CLIENT_SECRET}
    google:
      production:
        clientId: ${GOOGLE_CLIENT_ID}
        clientSecret: ${GOOGLE_CLIENT_SECRET}

catalog:
  rules:
    - allow:
        - Group
        - User
        - Component
        - API
        - Domain
        - Resource
        - Location
        - System
        - Template
  locations:
    - type: github-org
      target: https://github.com/grayc-de
    - type: github-discovery
      target: https://github.com/grayc-de
    - type: github-discovery
      target: https://github.com/inoa-io

kubernetes:
  serviceLocatorMethod:
    type: multiTenant
  clusterLocatorMethods: []

# http://backstage.io/docs/features/techdocs/configuration
techdocs:
  builder: local
  generator:
    runIn: local
  publisher:
    type: local
