name: Build

"on":
  workflow_dispatch: {}
  push:
    paths-ignore:
      - .github/workflows/docs.yaml
      - docs/**
      - mkdocs.yml
      - README.md

jobs:

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: colored
          strict: true

  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker://avtodev/markdown-lint:v1
        with:
          args: /github/workspace

  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@master
        with:
          dockerfile: packages/backend/Dockerfile
          ignore: DL3008  # ignore pinning of debian packages

  build:
    needs:
      - lint-yaml
      - lint-markdown
      - lint-dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: fetch branch main
        run: git fetch origin main
      - uses: actions/setup-node@v3.2.0
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: yarn.lock
      - run: yarn install --frozen-lockfile
      - run: yarn prettier:check
      - run: yarn lerna -- run lint --since origin/main
      - run: yarn tsc
      - run: yarn build
      - run: yarn build-image
      - uses: docker/login-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_ACTION_TOKEN }}
      - run: docker tag ghcr.io/grayc-de/backstage:latest ghcr.io/grayc-de/backstage:`date +"%Y%m%d-%H%M%S"`
        if: github.ref == 'refs/heads/main'
      - run: docker push ghcr.io/grayc-de/backstage --all-tags
        if: github.ref == 'refs/heads/main'
