name: Build

"on":
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.GIT_ACTION_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: crazy-max/ghaction-import-gpg@v4.1.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - run: printf 'backstage\n\n\'| npx @backstage/create-app --path backstage --skip-install
      - run: echo "COMMIT_MESSAGE=$(cat backstage/backstage.json | jq -r .version)" >> $GITHUB_ENV
      - uses: stefanzweifel/git-auto-commit-action@v4.13.1
        with:
          file_pattern: backstage/*
          commit_options: -S
          commit_user_name: kokuwa.io Bot
          commit_user_email: spampot+github.com+kokuwaio-bot@posteo.eu
          commit_author: kokuwa.io Bot <spampot+github.com+kokuwaio-bot@posteo.eu>
          commit_message: "${{ env.COMMIT_MESSAGE }}"
